-- pgsql_skeleton.sql
-- xead skeleton apache derby からの修正点
-- INT(10)　-> integer
-- SMALLINT(5)　-> smallint
-- LONG VARCHAR(32700)　-> text
-- DEFAULT '''''' -> DEFAULT ''

--
-- Table: AT010
--

CREATE TABLE AT010 (
    CDBUMON CHAR(5) DEFAULT '' NOT NULL,
    TXBUMON CHAR(30) DEFAULT '' NOT NULL,
    NRKANRISYA CHAR(5) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0,
    TXTEKIYO VARCHAR(300) DEFAULT ''
);

INSERT INTO AT010 (CDBUMON, TXBUMON, NRKANRISYA, UPDCOUNTER, TXTEKIYO) VALUES 
    ('00001', '部門１                           ', '11111', 0, '');

INSERT INTO AT010 (CDBUMON, TXBUMON, NRKANRISYA, UPDCOUNTER, TXTEKIYO) VALUES 
    ('00002', '部門２                           ', '11111', 0, '');


--
-- Table: AT011
--

CREATE TABLE AT011 (
    CDBUMON CHAR(5) DEFAULT '' NOT NULL,
    DTHAKKOUNENGETSU CHAR(6) DEFAULT '' NOT NULL,
    CDJYOUIBUMON CHAR(5) DEFAULT '' NOT NULL,
    DTSIKKOUNENGETSU CHAR(6) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0
);

INSERT INTO AT011 (CDBUMON, DTHAKKOUNENGETSU, CDJYOUIBUMON, DTSIKKOUNENGETSU, UPDCOUNTER) VALUES 
    ('00002', '201111', '00001', '999912', 0);


--
-- Table: AT020
--

CREATE TABLE AT020 (
    NRJYUGYOIN CHAR(5) DEFAULT '' NOT NULL,
    TXKANA CHAR(30) DEFAULT '' NOT NULL,
    TXKANJI CHAR(30) DEFAULT '' NOT NULL,
    KBKOYOU CHAR(5) DEFAULT '' NOT NULL,
    DTNYUSYA DATE NOT NULL,
    DTTAISYA DATE,
    UPDCOUNTER integer DEFAULT 0
);

INSERT INTO AT020 (NRJYUGYOIN, TXKANA, TXKANJI, KBKOYOU, DTNYUSYA, DTTAISYA, UPDCOUNTER) VALUES 
    ('11111', 'ﾔﾏﾓﾄﾖｳｺ                       ', '山本陽子                          ', '01   ', '2009-04-01', NULL, 1);


--
-- Table: AT021
--

CREATE TABLE AT021 (
    NRJYUGYOIN CHAR(5) DEFAULT '' NOT NULL,
    DTSYOZOKUNENGETSU CHAR(6) DEFAULT '' NOT NULL,
    CDBUMON CHAR(5) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0
);


--
-- Table: ZT010
--

CREATE TABLE ZT010 (
    IDVARIANT CHAR(20) DEFAULT '' NOT NULL,
    TXNAME CHAR(10) DEFAULT '' NOT NULL,
    TXTYPE CHAR(10) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0,
    TXVALUE CHAR(100) DEFAULT '' NOT NULL,
    TXREMARKS VARCHAR(500) DEFAULT ''
);

INSERT INTO ZT010 (IDVARIANT, TXNAME, TXTYPE, UPDCOUNTER, TXVALUE, TXREMARKS) VALUES 
    ('FIRST_MONTH         ', '年度第１月     ', 'NUMBER    ', 0, '4                                                                                                   ', '');

INSERT INTO ZT010 (IDVARIANT, TXNAME, TXTYPE, UPDCOUNTER, TXVALUE, TXREMARKS) VALUES 
    ('LAST_DAY            ', '締め日       ', 'NUMBER    ', 0, '25                                                                                                  ', '');

INSERT INTO ZT010 (IDVARIANT, TXNAME, TXTYPE, UPDCOUNTER, TXVALUE, TXREMARKS) VALUES 
    ('LOGIN_PERMITTED     ', 'ログイン認可フラグ ', 'STRING    ', 1, 'T                                                                                                   ', '');

INSERT INTO ZT010 (IDVARIANT, TXNAME, TXTYPE, UPDCOUNTER, TXVALUE, TXREMARKS) VALUES 
    ('COMP_NAME           ', '会社名       ', 'STRING    ', 3, 'ＸＸＸＸＸＸ社                                                                                             ', '');

INSERT INTO ZT010 (IDVARIANT, TXNAME, TXTYPE, UPDCOUNTER, TXVALUE, TXREMARKS) VALUES 
    ('COMP_LOGO           ', '会社ロゴ      ', 'STRING    ', 0, '<CURRENT>\db\image\Logo.PNG                                                                         ', '');


--
-- Table: ZT020
--

CREATE TABLE ZT020 (
    IDUSER CHAR(5) DEFAULT '' NOT NULL,
    TXMENUS CHAR(30) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0,
    DTVALID DATE NOT NULL,
    DTEXPIRE DATE NOT NULL,
    TXNAME CHAR(30) DEFAULT '' NOT NULL,
    NREMPLOYEE CHAR(5) DEFAULT '',
    TXPASSWORD CHAR(32) DEFAULT '' NOT NULL,
    TXEMAIL CHAR(40) DEFAULT ''
);

INSERT INTO ZT020 (IDUSER, TXMENUS, UPDCOUNTER, DTVALID, DTEXPIRE, TXNAME, NREMPLOYEE, TXPASSWORD, TXEMAIL) VALUES 
    ('11111', '20                            ', 1, '2011-04-01', '9999-12-31', '山本洋子                          ', '11111', 'f1b708bba17f1ce948dc979f4d7092bc', '                                        ');

INSERT INTO ZT020 (IDUSER, TXMENUS, UPDCOUNTER, DTVALID, DTEXPIRE, TXNAME, NREMPLOYEE, TXPASSWORD, TXEMAIL) VALUES 
    ('00000', 'ALL                           ', 3, '2000-01-01', '9999-12-31', 'システム管理者                       ', '     ', 'f1b708bba17f1ce948dc979f4d7092bc', '                                        ');


--
-- Table: ZT030
--

CREATE TABLE ZT030 (
    IDNUMBER CHAR(20) DEFAULT '' NOT NULL,
    TXPREFIX CHAR(4) DEFAULT '',
    NRCURRENT integer DEFAULT 0 NOT NULL,
    FGWITHCD CHAR(1) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0,
    NRNUMDIGIT NUMERIC(2) DEFAULT 0.0 NOT NULL
);

INSERT INTO ZT030 (IDNUMBER, TXPREFIX, NRCURRENT, FGWITHCD, UPDCOUNTER, NRNUMDIGIT) VALUES 
    ('NRSESSION           ', '    ', 1, 'F', 35, 7);


--
-- Table: ZT040
--

CREATE TABLE ZT040 (
    IDUSERKUBUN CHAR(20) DEFAULT '' NOT NULL,
    KBUSERKUBUN CHAR(5) DEFAULT '' NOT NULL,
    TXUSERKUBUN CHAR(20) DEFAULT '' NOT NULL,
    SQLIST CHAR(2) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0
);

INSERT INTO ZT040 (IDUSERKUBUN, KBUSERKUBUN, TXUSERKUBUN, SQLIST, UPDCOUNTER) VALUES 
    ('KBFLAG1             ', 'F    ', '対象外                 ', '02', 0);

INSERT INTO ZT040 (IDUSERKUBUN, KBUSERKUBUN, TXUSERKUBUN, SQLIST, UPDCOUNTER) VALUES 
    ('KBFLAG1             ', 'T    ', '対象                  ', '01', 0);

INSERT INTO ZT040 (IDUSERKUBUN, KBUSERKUBUN, TXUSERKUBUN, SQLIST, UPDCOUNTER) VALUES 
    ('KBKOYOU             ', '01   ', '正社員                 ', '01', 0);

INSERT INTO ZT040 (IDUSERKUBUN, KBUSERKUBUN, TXUSERKUBUN, SQLIST, UPDCOUNTER) VALUES 
    ('KBKOYOU             ', '02   ', 'パート                 ', '02', 0);

INSERT INTO ZT040 (IDUSERKUBUN, KBUSERKUBUN, TXUSERKUBUN, SQLIST, UPDCOUNTER) VALUES 
    ('KBCURRENCY          ', 'USD  ', 'USD                 ', '02', 1);

INSERT INTO ZT040 (IDUSERKUBUN, KBUSERKUBUN, TXUSERKUBUN, SQLIST, UPDCOUNTER) VALUES 
    ('KBCURRENCY          ', 'EUR  ', 'EUR                 ', '01', 1);


--
-- Table: ZT050
--

CREATE TABLE ZT050 (
    NRSESSION CHAR(7) DEFAULT '' NOT NULL,
    DTLOGIN TIMESTAMP NOT NULL,
    DTLOGOUT TIMESTAMP,
    IDUSER CHAR(5) DEFAULT '' NOT NULL,
    KBSESSIONSTATUS CHAR(3) DEFAULT '' NOT NULL,
    UPDCOUNTER integer DEFAULT 0,
    TXIPADDRESS CHAR(70) DEFAULT '' NOT NULL
);


--
-- Table: ZT051
--

CREATE TABLE ZT051 (
    NRSESSION CHAR(7) DEFAULT '' NOT NULL,
    SQPROGRAM smallint DEFAULT 0 NOT NULL,
    IDMENU CHAR(2) DEFAULT '' NOT NULL,
    IDPROGRAM CHAR(10) DEFAULT '' NOT NULL,
    TXPROGRAM CHAR(30) DEFAULT '' NOT NULL,
    DTSTART TIMESTAMP NOT NULL,
    DTEND TIMESTAMP,
    KBPROGRAMSTATUS CHAR(2) DEFAULT '',
    TXERRORLOG text DEFAULT '',
    UPDCOUNTER integer DEFAULT 0
);


--
-- Table: ZT060
--

CREATE TABLE ZT060 (
    DTSTART DATE NOT NULL,
    VLTAXRATE NUMERIC(3,2) DEFAULT 0.0 NOT NULL,
    UPDCOUNTER integer DEFAULT 0
);

INSERT INTO ZT060 (DTSTART, VLTAXRATE, UPDCOUNTER) VALUES 
    ('1997-04-01', 0.05, 0);

INSERT INTO ZT060 (DTSTART, VLTAXRATE, UPDCOUNTER) VALUES 
    ('1988-04-01', 0.03, 0);


--
-- Table: ZT070
--

CREATE TABLE ZT070 (
    DTOFF DATE NOT NULL,
    TXOFF CHAR(20) DEFAULT '',
    UPDCOUNTER integer DEFAULT 0
);


--
-- Table: ZT080
--

CREATE TABLE ZT080 (
    KBCURRENCY CHAR(5) DEFAULT '' NOT NULL,
    DTNEND smallint DEFAULT 0 NOT NULL,
    VLRATEB NUMERIC(10,3) DEFAULT 0.0 NOT NULL,
    VLRATEM NUMERIC(10,3) DEFAULT 0.0 NOT NULL,
    VLRATES NUMERIC(10,3) DEFAULT 0.0 NOT NULL,
    UPDCOUNTER integer DEFAULT 0
);

INSERT INTO ZT080 (KBCURRENCY, DTNEND, VLRATEB, VLRATEM, VLRATES, UPDCOUNTER) VALUES 
    ('EUR  ', 2010, 110.000, 110.000, 110.000, 0);

INSERT INTO ZT080 (KBCURRENCY, DTNEND, VLRATEB, VLRATEM, VLRATES, UPDCOUNTER) VALUES 
    ('EUR  ', 2011, 110.000, 110.000, 110.000, 0);

INSERT INTO ZT080 (KBCURRENCY, DTNEND, VLRATEB, VLRATEM, VLRATES, UPDCOUNTER) VALUES 
    ('USD  ', 2010, 85.000, 85.000, 85.000, 0);

INSERT INTO ZT080 (KBCURRENCY, DTNEND, VLRATEB, VLRATEM, VLRATES, UPDCOUNTER) VALUES 
    ('USD  ', 2011, 80.000, 80.000, 80.000, 0);


--
-- Table: ZT081
--

CREATE TABLE ZT081 (
    KBCURRENCY CHAR(5) DEFAULT '' NOT NULL,
    DTNEND smallint DEFAULT 0 NOT NULL,
    DTMSEQ smallint DEFAULT 0 NOT NULL,
    VLRATEB NUMERIC(10,3) DEFAULT 0.0 NOT NULL,
    VLRATEM NUMERIC(10,3) DEFAULT 0.0 NOT NULL,
    VLRATES NUMERIC(10,3) DEFAULT 0.0 NOT NULL,
    UPDCOUNTER integer DEFAULT 0
);


--
-- Primary Keys: 
--

ALTER TABLE AT010 ADD CONSTRAINT AT010_PK PRIMARY KEY (CDBUMON);
ALTER TABLE AT011 ADD CONSTRAINT AT011_PK PRIMARY KEY (CDBUMON, DTHAKKOUNENGETSU);
ALTER TABLE AT020 ADD CONSTRAINT AT020_PK PRIMARY KEY (NRJYUGYOIN);
ALTER TABLE AT021 ADD CONSTRAINT AT021_PK PRIMARY KEY (NRJYUGYOIN, DTSYOZOKUNENGETSU);
ALTER TABLE ZT010 ADD CONSTRAINT ZT010_PK PRIMARY KEY (IDVARIANT);
ALTER TABLE ZT020 ADD CONSTRAINT ZT020_PK PRIMARY KEY (IDUSER);
ALTER TABLE ZT030 ADD CONSTRAINT ZT030_PK PRIMARY KEY (IDNUMBER);
ALTER TABLE ZT040 ADD CONSTRAINT ZT040_PK PRIMARY KEY (IDUSERKUBUN, KBUSERKUBUN);
ALTER TABLE ZT050 ADD CONSTRAINT ZT050_PK PRIMARY KEY (NRSESSION);
ALTER TABLE ZT051 ADD CONSTRAINT ZT051_PK PRIMARY KEY (NRSESSION, SQPROGRAM);
ALTER TABLE ZT060 ADD CONSTRAINT ZT060_PK PRIMARY KEY (DTSTART);
ALTER TABLE ZT070 ADD CONSTRAINT ZT070_PK PRIMARY KEY (DTOFF);
ALTER TABLE ZT080 ADD CONSTRAINT ZT080_PK PRIMARY KEY (KBCURRENCY, DTNEND);
ALTER TABLE ZT081 ADD CONSTRAINT ZT081_PK PRIMARY KEY (KBCURRENCY, DTNEND, DTMSEQ);

